language: node_js
node_js:
  - "stable"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - node_modules

script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - yarn

  - yarn build

deploy:
  provider: pages
  github-token: $GH_TOKEN
  local_dir: build
  edge: true
  on:
    branch: master